# Example toml file as input for metasyn

config_version = "1.2"

[file]
name = "csv"  # The file is a CSV file

[file.arguments]  # Set arguments with which to read the file.
encoding = "windows-1252"
separator = ","

[[var]]
name = "PassengerId"
distribution = {unique = true}  # Notice booleans are lower case in .toml files.

[[var]]
name = "Name"
prop_missing = 0.1
description = "Name of the unfortunate passenger of the titanic."
distribution = {implements = "core.faker", parameters = {faker_type = "name", locale = "en_US"}}

[[var]]
name = "Fare"
distribution = {implements = "core.exponential"}

[[var]]
name = "Age"
distribution = {implements = "core.uniform", parameters = {lower = 20, upper = 40}}

[[var]]
name = "Cabin"
distribution = {implements = "core.regex", parameters = {regex_data = "[A-F][0-9]{2,3}"}}
privacy = {name = "disclosure", parameters = {partition_size = 21}}
