# Example toml file as input for metasyn

config_version = "2.0"

[[table]]
name = "single"
table_type = "dataframe"

[table.file_format]
name = "csv"  # The file is a CSV file
arguments = {encoding = "windows-1252", separator = ","}


[[table.var]]
name = "PassengerId"
distribution = {unique = true}  # Notice booleans are lower case in .toml files.

[[table.var]]
name = "Name"
prop_missing = 0.1
description = "Name of the unfortunate passenger of the titanic."
distribution = {name = "core.faker", parameters = {faker_type = "name", locale = "en_US"}}

[[table.var]]
name = "Fare"
distribution = {name = "core.exponential"}

[[table.var]]
name = "Age"
distribution = {name = "core.uniform", parameters = {lower = 20, upper = 40}}

[[table.var]]
name = "Cabin"
distribution = {name = "core.regex", parameters = {regex_data = "[A-F][0-9]{2,3}"}}

