# Example toml file as input for metasyn

[var.PassengerId]
unique = true  # Notice lower capitalization for .toml files.

[var.Name.distribution]
implements = "core.faker"
parameters = {faker_type = "name", locale = "en_US"}

[var.Fare.distribution]
implements = "core.exponential"

[var.Age.distribution]
implements = "core.uniform"
parameters = {low = 20, high = 40}

[var.Cabin.distribution]
implements = "core.regex"
parameters = {regex_data = "[A-F][0-9]{2,3}"}
