# Example toml file as input for metasyn

[general]
n_rows = 100


[var.PassengerId]
data_free = true
unique = true  # Notice lower capitalization for .toml files.
prop_missing = 0.0
description = "ID of the unfortunate passenger."
var_type = "discrete"

[var.PassengerId.distribution]
implements = "core.unique_key"
parameters = {consecutive = 1, low = 0}


[var.Name]
data_free = true
prop_missing = 0.1
description = "Name of the unfortunate passenger of the titanic."
var_type = "string"

[var.Name.distribution]
implements = "core.faker"
parameters = {faker_type = "name", locale = "en_US"}


[var.Cabin]
data_free = true
prop_missing = 0.2
var_type = "string"

[var.Cabin.distribution]
implements = "core.regex"
parameters = {regex_data = "[A-F][0-9]{2,3}"}
