# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Lint, test, documentation, plugins

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ develop ]
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8, 3.9, "3.10", "3.11", "3.12"]
        include:
            - os: macos-latest
              python-version: "3.11"
            - os: windows-latest
              python-version: "3.11"
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install ".[test]"
    - name: Lint with pylint
      run: |
        pylint metasyn
    - name: Lint with Ruff
      run: |
        ruff check metasyn
    - name: Check docstrings with pydocstyle
      run: |
        pydocstyle metasyn --convention=numpy --add-select=D417 --add-ignore="D102,D105"
    - name: Check types with MyPy
      run: |
        mypy metasyn
    - name: Check if documentation builds.
      run: |
        cd docs; make html SPHINXOPTS="--keep-going"
    - name: Test with pytest
      run: |
        pytest tests
    - name: Check notebook output
      if: ${{ matrix.os != 'macos-latest' }}
      run: |
        pytest --nbval-lax examples

    - name: Test basic example
      run: |
        python examples/basic_example.py

    - name: Test configuration example
      run: |
        pip install git+https://github.com/sodascience/metasyn-disclosure-control
        pip install .
        metasyn create-meta metasyn/demo/demo_titanic.csv --config examples/example_config.toml
