name: Release Dockerhub

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+" # when a new semver release is made

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: sodateam/metasyn:latest,sodateam/metasyn:${{github.ref_name}}